#!/bin/sh

cd $(dirname $0)
source $(dirname $0)/config

if [ $(pgrep -cx panel) -gt 1 ]; then
  printf "%s\n" "The lemon is already bruised." >&2
  exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc control --subscribe > "$PANEL_FIFO" &
echo "T" > "$PANEL_FIFO" &
conky -c ./panel_conky > "$PANEL_FIFO" &

cat "$PANEL_FIFO" \
      | ./panel_lemonbar \
      | lemonbar -p -d \
          -f "$FONTICONS" \
          -f "$MAINFONT" \
          -F "$FOREGROUND_COL" \
          -B "$BACKGROUND_COL" \
          -g "$PANEL_GEOMETRY" \
          -u "$LINEHEIGHT" \
          | while read line; do eval "$line"; done &
wait
