#!/bin/bash

## config
bspc config border_width        2
bspc config window_gap          12
bspc config top_padding         18
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config focused_border_color "#707070"
bspc config normal_border_color  "#2c2c2c"
bspc config active_border_color  "#2c2c2c"
bspc config presel_border_color  "#dcdcdc"

## get proper monitor?
bspc monitor -d    

bspc rule -a chromium desktop=^1
bspc rule -a firefox desktop=^1
bspc rule -a firefox-developer desktop=^1
bspc rule -a atom desktop=^2
bspc rule -a scudcloud desktop=^4
bspc rule -a spotify desktop=^4

## autostart
feh --bg-scale ~/Pictures/satellite.jpg &
~/.config/bspwm/panel/panel
